spring:
  application:
    name: springboot
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true # JPA가 생성하는 SQL 출력하기
    hibernate:
      ddl-auto: none
      # ddl-auto는 JPA는 테이블을 자동으로 생성하는 기능을 제공하는데, none을 사용하면 해당 기능을 끈다.
      # 반면에, create는 엔티티 정보를 바탕으로 테이블을 직접 생성해준다.
